### ISSUE TITLE
Results interpretation 

### ISSUE THREAD

**Issue by eleonora-mont** [MattWillFlood/EntropyHub#3]
Hi Matt, 

I managed to download and print some results with both ApEn and SampEn out of these calculations out of my data (attached):
[rh_limb_accx.csv](https://github.com/MattWillFlood/EntropyHub/files/10843694/rh_limb_accx.csv)

results_apen = EH.ApEn(X, m = 1, tau = 1, r = 0.77, Logx = np.exp(1))
results_sampen= EH.SampEn (X, m = 2, tau = 1, r = 0.2*np.std(X), Logx = np.exp(1))

Assuming I have done everything correctly, I am struggling to interpret the results.

The printed outputs are:
ApEn: (array([0.51792989, 0.19799168]), array([ 0.0019914 , -0.51593849, -0.71393017]));
SampEn: (array([0.16938967, 0.00739715, 0.00294948]), array([7401413., 7343049., 7317602.]), array([8767578., 7397568., 7339217.]));

I can read in the guideline that both functions generate two and three outputs respectively, however, I was expecting just one value instead of two for the first output of both functions. Would you be able to clarify this? 

Thanks!!!
Eleonora

**Comment by MattWillFlood** [comment]
Hi @eleonora-mont 
 
Thanks for your question!
If it is OK with you, I would prefer to answer this question via email because the GitHub issues tab is intended for raising issues regarding the software (e.g. bugs, errors, etc.). As this post concerns interpreting results, it isn't considered an issue.
I will follow up with you via email shortly to help you out.

As always, you can email help@entropyhub.xyz for support on any aspect of EntropyHub :)

Thanks,
Matt
