### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by furetosan** [MattWillFlood/EntropyHub#4]
Hi,

I'd expect K2 from the 1983 Grassberger paper to be zero for periodic signals, but:

EH.K2En(np.sin(np.linspace(-10,20,1000))) = 0.3..

TY!

**Comment by MattWillFlood** [comment]
Hi,

Yes in theory, for _perfectly_ periodic signals, K2 should ->0 as N -> inf.
However, this doesn't always work out always in practice because a _discretely sampled_ sinusoid (as in your case)  doesn't always revisit the exact same point in space. This will give some variance to the K2 estimate (i.e. not _perfectly_ periodic)
Furthermore, the default _r_ value used in EH.K2En is:  `r = 0.2*np.std(Sig)` 
This is commensurate tp the threshold parameter used to estimate the correlation sum. 
If you increase this value, the K2 estimate -> 0 as more delay embedding vectors are considered close in space.

```
y = np.sin(np.linspace(0,2*np.pi,10))[:-1]   # Creates a single period sinusoid of 9 samples
X = np.tile(y,400)   # Repeat this period so that the samples of each period are identifcal
EH.K2En(X,r=2.75)

K2 = (m=1) 0.02818676, (m=2) 0.05892571
```

Hope this helps!
Thanks,
Matt
