### ISSUE TITLE
Confusing error message and handling with Multiscale entropy

### ISSUE THREAD

**Issue by MarcelMartinsek** [MattWillFlood/EntropyHub#5]
The documentation for MSEn states that Sig must be a numpy vector of length>10. This appears to be inaccurate and in reality, the length requirement depends on the Scales parameter. 

For example, running the function with len(Sig)==11 and Scale==2 should be okay, according to the docs, but it throws and error "AssertionError: Sig:   must be a numpy vector".
The error is resolved if I use Sig of length 22(though i also find MSx[1]==inf in that case).

I would also note that for an error in length, the message "AssertionError: Sig:   must be a numpy vector" is a bit misleading.

Example code:
import EntropyHub as eh
msobj = eh.MSobject("SampEn", m = 2, tau = 1, Logx = np.exp(1))
MSx, Ci = eh.MSEn(np.random.randn(22),Mbjx=msobj, Scales = 2, Methodx = "coarse", RadNew = 0, Plotx = True)
MSx, Ci = eh.MSEn(np.random.randn(10),Mbjx=msobj, Scales = 2, Methodx = "coarse", RadNew = 0, Plotx = True)

**Comment by MattWillFlood** [comment]
Thanks for the feedback :)
There are a couple of things to explain about what is happening here.

1. The MSEn function, like all multiscale entropy functions in EntropyHub, employs the function of the underlying entropy method. In the case above, this is `SampEn()`. All of the underlying functions (both Base and Cross entropies) require the input time series to be >10 samples long. Thus, the reason that you are receiving this particular error message with `MSEn()`, is because at each increasing time scale, the length of the input series is reduced. In the case of coarse-graining, N is halved for each increasing scale. This is why you receive in `inf` when N==22, because at scale 2, N'==11.

2. _Most_ of the entropy methods in EntropyHub are based on conditional entropy and not the standard formula for Shannon entropy (compare Eqs.1 and 2 [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0259448)). The Sample Entropy algorithm is one such method, which requires sufficiently long time series (N of order 10^3) to be not just statistically accurate/mathematically meaningful, but to avoid cases when no embedding vectors are considered matches. Given that you have used _random sequences_  of very short length, this will often produce `inf` and `nan` values as outputs. It is **_highly_** unusual to estimate SampEn with N < 100.

Nevertheless, your point is valid that  "AssertionError: Sig: must be a numpy vector" is not informative for the user. I will try to update this as soon as possible.

Thanks,
Matt
